### ISSUE TITLE
status_command process exited unexpectedly (exit 1)

### ISSUE THREAD

**Issue by tokisuno** [jthistle/py3spotifystatus#1]
pretty sure i installed everything right. the path is where the file is located (nvim was autofilling it for me while typing so it's real), and i don't think there are any spelling mistakes in the i3 status config file either. 

![image](https://github.com/jthistle/py3spotifystatus/assets/85533116/bde111be-1695-439b-9771-a460e33ed435)

**Comment by jthistle** [comment]
Hi Lucas - can you run the script in your terminal and paste the output here? Thanks.

All that `status_command process exited unexpectedly (exit 1)` means is that the script errored - to see the error message you need to run it in the terminal.

**Comment by jthistle** [comment]
Any luck @tokisuno?

**Comment by tokisuno** [comment]
> 

shit man haven't been on github in a bit. no i didn't and ended up just going w/ an i3blocks script instead.

**Comment by jthistle** [comment]
OK, no worries. Closing this then as I can't reproduce.
